---
author: admin
date: 2011-12-23 14:43:14
slug: r-data-analysis-examples
title: R数据分析实例
wordpress_id: 1023
categories:
- R
tags:
- Logistic回归
- 稳健回归
---

##### 回归模型（Regression Models）





	
  * [稳健回归（Robust Regression）](http://yishuo.org/2011/12/r-data-analysis-examples-robust-regression/)




##### 二分变量及分类模型（Models for Binary and Categorical Outcomes）





	
  * Logistic回归（Logistic Regression）

	
  * 确切Logistic回归（Exact Logistic Regression）

	
  * 多分类Logistic回归（Multinomial Logistic Regression）

	
  * 顺序Logistic回归（Ordinal Logistic Regression）

	
  * Probit回归（Probit Regression)




##### 计数模型（Count Models）





	
  * 泊松回归（Poisson Regression）

	
  * 负二项式回归（Negative Binomial Regression）

	
  * 零膨胀泊松回归（Zero-inflated Poisson Regression）

	
  * 零膨胀负二项式回归（Zero-inflated Negative Binomial Regression）

	
  * 零截断泊松回归（Zero-truncated Poisson）

	
  * 零截断负二项式回归（Zero-truncated Negative Binomial)




##### 双侧截断回归（Censored and Truncated Regression）





	
  * Tobit回归（Tobit Regression）

	
  * 截断回归（Truncated Regression）

	
  * 区间回归（Interval Regression）




##### 多因素分析（Multivariate Analysis）





	
  * 单边多元方差分析（One-way MANOVA）

	
  * 判别函数分析（Discriminant Function Analysis）

	
  * 典型相关分析（Canonical Correlation Analysis）

	
  * 多元回归分析（Multivariate Multiple Regression）




##### 效能/样本量分析（Power Analysis / Sample Size）





	
  * 单样本t检验（Single-sample t-test）

	
  * 配对样本t检验（Paired-sample t-test）

	
  * 独立样本t检验（Independent-sample t-test）

	
  * 独立比例分析(Two Independent Proportions)

	
  * 单侧方差分析（One-way ANOVA）

	
  * 多元回归（Multiple Regression）

	
  * 参数精度分析（Accuracy in Parameter Estimation）

	
  * Logistic回归（Logistic Regression）




##### 其它





	
  * 潜类分析（Latent Class Analysis）



