[build]
command = 'hugo'
publish = 'public'

[build.environment]
HUGO_VERSION = '0.147.0'

[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
command = 'hugo -b $URL'  
[context.production.environment]
HUGO_ENV = 'production'
