---
title: 科斯对现代经济学的批评
categories:
- economics
tags:
- economics
- 科斯
- 实体
- 产业
---
  
当下的经济学，无论是印刷在教课书上的，抑或是讲台上口授的，都与商业关系疏远，与企业家精神更是差以千里。经济学与商业生活的背离已经到了触目惊心甚至糟糕的地步。

往昔并非如此。回想现代经济学诞生之初，亚当斯密将其设想为一门研究“国家财富性质与原因”的学问。他的极具开创性的著作——《国富论》——被商人们——尽管亚当斯密因为他们贪婪、短视和其他缺点而赤裸裸地蔑视他们——广为阅读。该著作激发并引了导政客们针对贸易和其它经济政策的争论。当时的学术社区非常之小，以至于经济学家们不得不通过著作向公众们大声疾呼。甚至在近于20世纪的端口，阿尔弗雷德马歇尔依然努力将经济学定义为一门“研究财富和人类行为”的学问。当时的经济学保持住了与产业界的联系。

20世纪，经济学将自己巩固成为一门职业。经济学家们可以专为别人著述。同时，经济学领域经历了一次典范转移，其逐步将自己打造为一个探讨经济化行为的理论分支，并逐步放弃了把真实经济运行作为研究对象的传统。眼下，产出理论在经济学中已被边缘化，取而代之的流行范式是研究稀缺资源配置的均衡性。经济学家用以分析商业公司的工具过于抽象和投机，这些工具对于企业家和经理们试图将经典产品低价销售给消费者的常态努力少有帮助。

经济学与真实经济运行的脱离极大地伤害了商业和学术。鉴于经济学家难以提供务实的观点，企业家和经理们将不得不依靠自身的商业头脑、个人判断和经验来进行决策。经济危机期间，当商业领袖丧失自
信，他们经常想要向政治力量求助。政府正日益被看作是经济问题、创新和就业的拯救者。

因为经济学正日益沦为政府用以管理经济的便捷手段，当公众试图寻找“经济如何运转”的真知时，已无法再向经济学这一工具求助。鉴于经济学不再植根于对真实经济运行的系统性研究，其也难担此任。在人类的大部分历史中，家庭和部落都主要依靠于周遭已存的经济环境；他们与其他家庭或者部落以及外部世界的联系十分贫乏且断断续续。商业社会的崛起彻底扭转了这一情形。如今，一个现代市场经济及其劳动力的精细分工依赖于一个不断扩大的贸易网。这需要一个错综复杂的社会机构来协调市场机制和公司的各种边界。在现代经济日益机构密集之时，将经济学理论简化为价格理论无异于自找泥潭；当经济学沦为硬科学，无视社会、历史、文化和政治对经济运行的影响时，无异于自取灭亡。

重建贫瘠的经济学领域与经济联系已迫在眉睫。市场经济正在中国、印度、非洲和其他地方纷纷兴起，这意味着一个充满着企业家精神的时代的到来。对于经济学家而言，这是一个千载难逢的机会，经济学家得以借此机会研究市场经济是如何在不同的文化、机构和组织形态中建立的。然而，只有当经济学家调整自身，重新将人作为人，将经济体系作为经济体系来研究时，才能有所收获。
