---
title: 孤独的投资者卡洛·坎奈尔
categories:
- investment
tags:
- 卡洛·坎奈尔
---

<b>发布日期:2013-09-01 作者:邓一硕</b>

卡洛·坎奈尔(CarloCannell)是一位名副其实的价值投资者，因拥有一套独特的价值选股方法而闻名。1992年，他在旧金山创建专注于股票多空策略的坎奈尔资产管理公司(CannellCapitalLLC)，成立以来旗舰基金汤加基金(TongaFund)的年均收益率维持在20%左右的水平。

诱人的回报率自然吸引了众多投资者，不过坎奈尔竭力将资产管理规模控制在8亿美元的水平。作为小盘股捡股者的他不可能在运营大量资金的情况下仍然维持着超高回报率。过去几年，他先后退还了投资者2.5亿美元资金。

“分析师比例”指标

坎奈尔认为孤独者才能成为更好的基金经理，这一点恰好体现在他关注的对象往往是其他投资者从不关注的领域。巴菲特曾说，理性的人总是比较孤独的，但对于投资者来说，却是最重要的素质。

坎奈尔与其他价值投资者的另一个共同特质，是认为市场并非有效，因此他宁愿在那些“人迹罕至”的市场角落里“深耕”。

“我认为无效率的市场比有效率的市场能够提供更大的潜在回报。由于有大量的公司信息分布不合理，这导致了市场失效。因此，我们要用大量时间去发掘很大程度上被投资市场忽视的投资价值。”坎奈尔这样说道。

目前，美国有超过13000家公司必须向美国证监会提交各种形式的报告以及做出信息披露，其中大多数公司都缺乏研究机构的持续跟踪。坎奈尔把“缺乏持续跟踪”定义为只有三个或者更少的卖方分析师定期发布公司的预期收益报告，因此这些公司缺乏常规的信息流动。

根据坎奈尔的经验，缺乏信息流动会导致市场估值跟公司的实际内在价值间差异更大。基于这样的理念，坎奈尔创造了一个所谓的“分析师比例”指标。这项指标跟踪上市公司的分析师人数。

“我们认为一个公司的研究者越少越好。在我们投资组合中大约有65%的企业几乎不被任何分析师关注。”坎奈尔解释道。

坎奈尔并不认为根据这项指标筛选个股是最科学的，但的确是筛选最具价值产品的起点。

接着，坎奈尔会根据一些传统指标进一步进行筛选。这些指标包括：较低的市净率、较低的账面价值溢价或者折价、市盈率小于股本回报率以及持续产生现金流大于资本支出等。

位于美国俄亥俄州利普西克的恩尼斯(Ennis)公司是坎奈尔喜欢的典型小盘股。这家公司是一家有着悠久历史的印刷企业。

坎奈尔称：“我们认为这家企业有着非常好的管理机制。他们的竞争力非常强，非常自律，高管也十分诚实。此外，只有两个非常小的机构研究员在研究这家公司。这个公司从不开季度电话会议，也很少对产品进行宣传，正是我们喜欢的公司。”

坎奈尔从2001年到2006年，一直持有这家公司。在这期间，公司的股价从每股7.5美元一路上涨至26美元。

“古怪”的投资理念和方法

除了传统的价值投资分析外，坎奈尔还拥有一些“古怪”的投资理念和方法。

“投资者其实和放射科医生、机械工程师或者驾驶员一样，通过某种外在的模式来对事物的本质进行判断。而不同水平的人找出外在形态之间关联性的能力不一样。我认为通过这种能力来甄选股票就是我们的优势所在。”坎奈尔这样说道。

坎奈尔用一个例子说明这种能力的具体表现：“我们在对潜在的卖空对象进行研究的过程中发现，如果一家公司是由非‘六大’会计师事务所进行财务审计，且这家公司的库存比例正不断下降，这时候公司现金流和净收入之间的差距会否扩大与分析师会否研究这家公司有很大关联性。如果分析师对一家公司的研究力度加大，那么这个公司就可能成为我们潜在的做空对象。”

2010年初，坎奈尔就指出，他已经开始做空德国的太阳能公司。主要原因是，这个行业得到的政府补贴越来越少，其债务规模也达到了极高水平。

此外，坎奈尔还有更为“独到”的研究指标。他指出，预付指标是他非常关注的数据之一，而这个指标经常被投资者忽略。

“公司经常说他们的预付资产一般用于保险、广告或进行商战，但这项资金其实经常用于进行行贿。因此这个数据起伏很大，有时会给公司财务带来很大麻烦。如果这个数据伴随的是毛利率下降，那么投资者就需要提高警惕了。因为在下一季的财报中，会计很有可能会加大销售成本，来掩饰他们在预付资金方面的漏洞。”

在对公司进行财务分析之后，坎奈尔接下来需要做的，是在“信息分布不合理”的情况下，对买入公司的未来发展进行一个系统评估。

“对于这一点，我们的做法是聘用一个曾在CNBC(美国全国广播公司财经频道)工作过的记者，他每天的工作就是逛街，包括塔吉特百货(Targets)和百思买(BestBuys)等等，然后发现市场的细微变化。”坎奈尔这样说道，“此外我们也订阅大量的行业杂志，比如石油化工行业、殡葬行业等等。”

坎奈尔近期向SEC提交的13F档案显示，他在截至2013年3月31日的第一季度中，前三大重仓股分别是价值媒体公司(ValuevisionMediaInc)、信息交换解决方案供应商内部链接控股公司(IntraLinksHoldings)，以及多频道电信公司(MultibandCorp)。

由于坎奈尔非常看重公司的增长潜能，他也不可避免会通过对管理层施压，来改善股价表现。这个时候的他更像是一名积极的“股东行动主义”投资者。

投资顺应自然法则

在投资方法之外，坎奈尔的古怪念头也随处可见。他被其他价值投资人熟知是因为在2009年的价值投资大会时，曾经将灭绝的物种与投资相比较。

他指出，史特拉海牛(Hydrodamalisgigas)是一个已经灭绝了的生物。18世纪中叶之前，人类还未穿过白令海峡，这些海牛生活在北太平洋的海岸线上。自从有1500人徒步来到这里后，史特拉海牛被发现，并被人类猎杀，它们在短短27年之后就灭绝了。

这个道理可以引申到投资中去。“物种就好比是上市公司。一些公司在大环境变化的过程中，总会经历比别人更长的一段适应期，如果不能适应，那么就会灭绝。比如说，餐饮公司受经济危机的冲击要比一些非周期的行业要大。

坎奈尔认为，巴菲特在投资过程中总会利用类似大自然的天然法则，从而规避很多不必要的风险。因此，利用自然规律获益远比想尽一切办法找出下一个可口可乐公司要容易得多。

### 坎奈尔小档案

坎奈尔1963年出生在加利福尼亚州，父亲彼得·坎奈尔(PeterB.Cannell)和祖父都是投资者，并各自成立了自己的资产管理公司。在这样的家庭背景影响下，坎奈尔走上投资之路并不意外，但他并非一开始就热爱投资。

坎奈尔的大学生涯在普林斯顿大学度过，他一开始选择了古典文学专业，但很快发现自己并不喜欢，于是转向了社会学专业。1986年毕业之后，他只身前往南太平洋的岛国——斐济，成为一名自由职业的记者，此后又先后为两家日本公司服务。

1988年，他开始自己创业，开了一家开发设计桌面音乐乐谱的公司，缺乏管理经验的他很快意识到自己需要到商学院深造，于是选择了牛津大学的坦普顿学院(TempletonCollege)，这段求学经历真正促使他走向了投资行业。

“我在牛津那段时间投入到投资中，而且是以一种非常学术和理论化的视角来进行投资。”坎奈尔这样说道，“我做了很多关于市场有效论的研究，非常了解这个假说什么时候会失效。在这些研究下，我的投资哲学得以形成，并沿用至今。”

1992年，在获得MBA学位后不久，坎奈尔创建了坎奈尔资产管理公司。也正是这一年，他与妻子珍妮弗·布拉德利(JenniferT.Bradley)喜结良缘，婚后他们育有三个子女。(张愎)

