---
title: 几本关于R的书籍
categories:
- R
tags:
- R
- 书籍
---

最近出版社的朋友推荐了几本在亚马逊上卖的火热的R书籍，都是比较经典的著作。先记下来，回头来写一下简单介绍。

    1.Introductory Time Series with R (Use R!) 
    Paul S.P. Cowpertwait (Author), Andrew V. Metcalfe (Author) 
    Paperback: 272 pages 
 	Publisher: Springer; 2009 edition (June 9, 2009) 
 	Language: English 
 	ISBN-10: 0387886974 
 	ISBN-13: 978-0387886978 
 	Product Dimensions: 6.1 x 0.6 x 9.2 inches 
 	Shipping Weight: 10.4 ounces (View shipping rates and policies) 
 	Average Customer Review: 4.2 out of 5 stars  See all reviews (13 customer reviews) 
 	Amazon Best Sellers Rank: #213,352 in Books (See Top 100 in Books) 


 	2.Time Series Analysis: With Applications in R (Springer Texts in Statistics) 
 	Paperback: 505 pages 
 	Publisher: Springer (November 19, 2010) 
 	Language: English 
 	ISBN-10: 1441926135 
 	ISBN-13: 978-1441926135 
 	Product Dimensions: 7 x 1.2 x 9.2 inches 
 	Shipping Weight: 1.9 pounds (View shipping rates and policies) 
 	Average Customer Review: 4.4 out of 5 stars  See all reviews (8 customer reviews) 
 	Amazon Best Sellers Rank: #257,246 in Books (See Top 100 in Books) 


	3. Financial Risk Forecasting: The Theory and Practice of Forecasting Market Risk with Implementation in R and Matlab (The Wiley Finance Series)
 	Hardcover: 296 pages 
 	Publisher: Wiley; 1 edition (April 25, 2011) 
 	Language: English 
 	ISBN-10: 0470669438 
 	ISBN-13: 978-0470669433 
 	Product Dimensions: 6.9 x 0.8 x 9.8 inches 
 	Shipping Weight: 1.4 pounds (View shipping rates and policies) 
 	Average Customer Review: 3.7 out of 5 stars  See all reviews (3 customer reviews) 
 	Amazon Best Sellers Rank: #274,341 in Books (See Top 100 in Books) 


	4.Software for Data Analysis: Programming with R (Statistics and Computing) John Chambers (Author) 
 	Paperback: 512 pages 
 	Publisher: Springer (November 23, 2010) 
 	Language: English 
 	ISBN-10: 1441926127 
 	ISBN-13: 978-1441926128 
 	Product Dimensions: 6.1 x 1.3 x 9.2 inches 
 	Shipping Weight: 1.6 pounds (View shipping rates and policies) 
 	Average Customer Review: 4.1 out of 5 stars  See all reviews (7 customer reviews) 
 	Amazon Best Sellers Rank: #51,410 in Books (See Top 100 in Books) 




