---
title: apply函数族入门
author: MatrixSpk
date: '2011-11-09'
slug: apply-family
categories:
- R
tags:
- apply
- r
- 翻译
---

在任何一个R语言问答网站或者论坛，你都能看见这样的问题：

> 
Q:如何用循环做【...各种奇怪的事情...】
A:不用用循环哦，亲！apply函数可以解决这个问题哦，亲！

上面答案中提到的这个神奇的apply函数到底是什么？下面通过一些简单的操作示范一下。

打开R，敲入??apply函数，选定base包部分你会看到下面的东西：

```
base::apply Apply Functions Over Array Margins
base::by Apply a Function to a Data Frame Split by Factors
base::eapply Apply a Function Over Values in an Environment
base::lapply Apply a Function over a List or Vector
base::mapply Apply a Function to Multiple List or Vector Arguments
base::rapply Recursively Apply a Function to a List
base::tapply Apply a Function Over a Ragged Array
```

下面一一示范。

* apply

先看看帮助文档中对其的描述：

> “Returns a vector or array or list of values obtained by applying a function to margins of an array or matrix. ”

好吧，vector、array和function是神马我都明白，margins是什么？我来翻译一下吧，margins为1时是指行，margins为2时是指列，如果是c(1:2)，好吧，这个啰嗦的举动，指的是整个array或者matrix。

例子如下:

```{r}
#创建一个10行2列的矩阵
m <- matrix(c(1:10,11:20),nrow=10,ncol=2)

#求m的每一行的均值
apply(m,1,mean)

#求m的每一列的均值
apply(m,2,mean)

#将m的每个值除以2
apply(m,1:2,function(x) x/2)
```

最后一个例子仅仅是为了示范，我们有更简单的方法一秒钟实现。

```{R}
m/2
```

* by

帮助文档中的描述：

> 
“Function by is an object-oriented wrapper for tapply applied to data frames. ”


事实上，by的功能绝不是这一句话所能描述的。接着读下去，你会看到

> “A data frame is split by row into data frames subsetted by the values of one or more factors, and function FUN is applied to each subset in turn. ”


这里，我们用一个带有定性变量的数据进行示范。这个数据集就是著名的iris。

```{R}
attach(iris)
head(iris)

#根据Species分类，求前4个变量的均值
by(iris[,1:4],Species,mean)

```

其实，就是根据一个定性变量将数据分为若干个子集，再对各子集进行apply操作。

* eapply

帮助文档的描述：

> “eapply applies FUN to the named values from an environment and returns the results as a list. The user can request that all named objects are used (normally names that begin with a dot are not). The output is not sorted and no enclosing environments are searched. ”

有理解这句话，重点是理解environment这个东西。environment相当于是R里面的一个小系统，这个系统包含有自己的变量和函数等内容。

用一个简单的例子来示范：

```{R}
#创建一个新的environment
e=new.env()
#在e中创建两个变量
e$a=1:10
e$b=11:20
#求e中变量的均值
eapply(e,mean)
```

一般人儿可能不常用environment这个东西。不过，Bioconductor们是例外。

* lapply

帮助文档的描述：

> “lapply returns a list of the same length as X, each element of which is the result of applying FUN to the corresponding element of X. ”

这是apply函数的帮助文档中最简明扼要的一个。直接给示范：

```{R}
#创建一个list
l=list(a=1:10,b=11:20)
#计算list中每个元素的均值
lapply(l,mean)

#计算list中每个元素的和
lapply(l,sum)
```

lapply的文档中让我们进一步参考sapply、vapply和replicate。那我们走去看看。

* sapply

帮助文档的描述：

>  “sapply is a user-friendly version and wrapper of lapply by default returning a vector, matrix or, if simplify="array", an array if appropriate, by applying simplify2array(). sapply(x, f, simplify=FALSE, USE.NAMES=FALSE) is the same as lapply(x,f). ”

上面一堆简单说就是，lapply返回的是一个含有两个元素$a和$b的list，而sapply返回的是一个含有元素[["a"]]和[["b"]]的vector，或者列名为a和b的矩阵。

示范如下：

```{R}
#创建一个list
l=list(a=1:10,b=11:20)
#用sapply求均值
l.mean=sapply(l,mean)
#观察返回结果的类型
class(l.mean)

l.mean[['a']]

```

* vapply

帮助文档的描述：

> “vapply is similar to sapply, but has a pre-specified type of return value, so it can be safer (and sometimes faster) to use.”

直接示范：

```{R}
l=list(a=1:10,b=11:20)
#用vapply函数计算五分位数
l.fivenum=vapply(l,fivenum,c(Min.=0,"lst Qu."=0,Median=0,"3rd Qu."=0,Max.=0))
class(l.fivenum)
#结果
l.fivenum

```

从结果可以看到，vapply返回的是一个矩阵。矩阵的列名是list的元素，行名取决于函数的输出结果。

* replicate

帮助文档的描述:

>“replicate is a wrapper for the common use of sapply for repeated evaluation of an expression (which will usually involve random number generation). ”

replicate是一个非常强大的函数，它有两个强制参数：replications,即操作的重复次数；function，及要重复的操作。还有一个可选择参数：simplify=T，是否将操作结果转化为vector或者matrix。

示范：

```{R}
replicate(10,rnorm(10))
```

* mapply

帮助文档的描述：

>“mapply is a multivariate version of sapply. mapply applies FUN to the first elements of each ... argument, the second elements, the third elements, and so on. Arguments are recycled if necessary. ”

如果你认真看看mapply的帮助文档的话，我打赌你会看到头大。这里给看官两个简单的例子：

```{R}
l1=list(a=1:10,b=11:20)
l2=list(c=21:30,d=31:40)
l1
l2
#计算l1,l2中各元素的和
mapply(sum,l1$a,l1$b,l2$c,l2$d)
```

竖直看下来，加总就得到了上面的结果。

* rapply

帮助文档的描述：

> “rapply is a recursive version of lapply. ”

这个描述是史上最差描述之一。因为rapply跟recursive并没有太大关系。rapply的创造性在于提供了一个结果输出形式的参数。

示范：

```{R}
#创建list
l=list(a=1:10,b=11:20)
#计算l中元素的log2
rapply(l,log2)

#将结果的输出形式设定为list

rapply(l,log2,how="list")

#计算均值
rapply(l,mean)

rapply(l,mean,how="list")
```

综上，rapply函数的输出结果取决于函数和how参数。当how="list"时，数据的原始结构被保留，否则，输出结果被转化为vector。

当然，看官还可以将classes函数传递给rapply函数。例如在混合型list中，可以通过classes=numeric，是的函数子对数字型元素进行操作。

* tapply

帮助文档的描述：

>“Apply a function to each cell of a ragged array, that is to each (non-empty) group of values given by a unique combination of the levels of certain factors.”

语焉不详。翻译一下大概是：

“tapply(X, INDEX, FUN = NULL, ..., simplify = TRUE)”中的“X”是
“an atomic object, typically a vector.”，而“INDEX”是“list of factors, each of same length as X. The elements are coerced to factors by as.factor.”

依然以iris数据集为例示范一下：

```{R}
attach(iris)
#根据sprcies进行分类，计算petal的均值
tapply(iris$Petal.Length,Species,mean)
```

简短的总结：

这里给出的都是极其简单的例子，基于最简单的数据，和最简单的函数。因为对于每一个操作而言，看官都可查看数据的操作前状态和操作后状态，这样便于看官知道，操作到底对数据干了什么事情。

当然了，apply函数的功能不限于文中介绍的这些，进一步的功用期待看官自己去挖掘。

给出几个使用apply函数的建议，在使用之前应当思考：

* 原始数据是什么类型？vector?matrix?data frame?....
* 想对原始数据的哪些子集进行操作？行?列？所有元素？....
* 操作将返回什么结果？原始数据的结构是如何变化的？

只是一个老生常谈的关于“输入——操作——输出”的故事：你有什么？你想要什么？两者之间需要什么？
