---
title: 债券业务的会计处理
categories:
- life
tags:
- 债券
- 会计处理
---

与债券业务相关的新会计准则出台后在现实业务中出现一些较难处理的问题，本文尝试通过举例来说明个人对新准则的一些理解，本文中的案例是建立在以下基础之上：

* 严格遵守:
  * 《企业会计准则第22号----金融工具的确认和计量》
  * 《企业会计准则第23号----金融资产转移》
  * 《企业会计准则第24号----套期保值》
  * 《企业会计准则第37号----金融工具列报》
  * 《企业会计准则第38号----首次执行企业会计准则》等准则
  * 《企业会计准则----应用指南》
* 本文中的公允价值假设均为已知数据，在此不做公允价值的深度探讨。
* 为方便举例，本文仅对明确进行了四分类的债券进行实例分析;案例中的债券数据仅以本文中提供的为准，不参考任何分析软件及其他方式提供的数据。

##	新准则下的日计表案例格式

序号	资产类	序号	负债类
　	流动资产	　	流动负债
　	
一	交易类金融资产	一	交易性金融负债

1	交易性金融资产---成本	            1	交易性金融负债---成本
2	交易性金融资产---公允价值变动	    2	交易性金融负债---公允价值变动
3	应收利息---交易性金融资产应收利息	3	应付利息---交易性金融负债应付利息

二	买入返售金融资产（逆回购）	二	卖出回购金融资产款（正回购）
1	买入返售金融资产（逆回购）	1	卖出回购金融资产款（正回购）
2	应收利息---逆回购应收利息	2	应付利息---正回购应付利息
三	银行存款	三	系统内拆借资金
　	非流动资产	四.	应交税金---应交营业税金及附加
　	
四	可供出售金融资产	　	　
1	可供出售金融资产---成本 	　	　
2	可供出售金融资产---利息调整 	　	　
3	可供出售金融资产---公允价值变动 	　	　
4	应收利息---可供出售金融资产应收利息	　	　
5	可供出售金融资产---应计利息（贴现债）	　	　
五	持有至到期投资	　	　
1	持有至到期投资---成本 	　	　
2	持有至到期投资---利息调整 	　	　
3	应收利息---持有至到期投资应收利息	　	　
4	持有至到期投资---应计利息（贴现债） 	　	　
5	持有至到期投资减值准备	　	　
　	资产负债共同类	　	资产负债共同类
六	衍生工具	五	衍生工具
1	衍生工具---远期买入交易	1	衍生工具---远期卖出交易
　	小计	　	小计
七	支出类	六	收入类
1 	利息支出---正回购利息支出	1	利息收入--逆回购利息收入
2 	系统内拆借利息支出	2	代理手续费收入
3 	代理手续费支出	3	投资收益-国债利息收入
4 	营业税金及附加	4	投资收益-金融债券利息收入
5 	资产减值损失	5	其他利息收入
 		6	公允价值变动损益
　	小计	　	小计
　	　	七	所有者权益
　	　	1	利润分配-未分配利润
　	　	2	资本公积---其他资本公积
　	　	3	盈余公积---法定盈余公积
　	　	4	盈余公积---任意盈余公积
　	总计	　	总计

## 质押式正回购会计核算案例

质押式正回购会计核算
一、	科目设置
1、卖出回购金融资产款
2、应付利息---正回购应付利息
3、利息支出----正回购利息支出

二、实例
质押式正回购会计分录（卖出回购金融资产款）
成交日期：2007-5-10      全国银行间同业拆借中心银行间质押式回购正回购成交通知单
正回购方	甲方
逆回购方	乙方
回购利率（%）	3	回购期限（天）	183
券面总额（万元）	10000	成交总金额（元）	100,000,000
到期还款总额（元）	101,500,000	手续费（元）	200
首期结算方式	券款对付	到期结算方式	券款对付
首次交割日	2007-5-10	到期交割日	2007-11-9
1、	从行外融入正回购资金时，融入资金1亿元，回购利率3%，回购期限2007-5-10至2007-11-09  6个月，回购利息150万，2007-5-10首期会计处理：
借：银行存款                                     100,000,000
  贷：卖出回购金融资产款                         100,000,000

2、按月末计提应收利息（资产负债表日，按照计算确定的买入返售金融资产的利息收入）
借：利息支出----正回购利息支出                    250,000
  贷：应付利息----应付正回购利息                  250,000
连提6个月，5月31日、6月30日、7月31日、8月31日、9月30日、10月31日
25万*6个月=1,500,000

3、2007-11-9到期（返售日）
借：卖出回购金融资产款                            100,000,000
应付利息----应付正回购利息                     1,500,000
（或）利息支出---正回购利息支出                     0
  贷：银行存款                                    101,500,000
     

## 质押式逆回购会计核算案例

质押式逆回购会计分录
一、	科目设置
1、买入返售金融资产
2、应收利息----逆回购应收利息
3、利息收入----逆回购利息收入

二、实例
成交日期：2007-5-10      全国银行间同业拆借中心银行间质押式回购逆回购成交通知单
逆回购方	甲方
正回购方	乙方
回购利率（%）	3	回购期限（天）	183
券面总额（万元）	10000	成交总金额（元）	100,000,000
到期还款总额（元）	101,500,000	手续费（元）	200
首期结算方式	券款对付	到期结算方式	券款对付
首次交割日	2007-5-10	到期交割日	2007-11-9

2、	向外放出逆回购资金，借出资金1亿元，回购利率3%，回购期限2007-5-10至2007-11-09  6个月，回购利息150万，2007-5-10甲方首期会计处理：
借：买入返售金融资产                    100,000,000
  贷：银行存款                          100,000,000

2、按月末计提应收利息（资产负债表日，按照计算确定的买入返售金融资产的利息收入）
借：应收利息---应收逆回购利息            250,000
  贷：利息收入—逆回购利息收入          250,000
连提6个月，5月31日、6月30日、7月31日、8月31日、9月30日、10月31日
25万*6=150,000

3、2007-11-9到期（返售日）
借：银行存款
  贷：买入返售金融资产                  100,000,000
      应收利息---应收逆回购利息          1,500,000
      利息收入---逆回购利息收入          0


## 交易性金融资产会计核算案例

交易性金融资产会计核算

一、	科目设置
1、交易性金融资产---成本
2、交易性金融资产---公允价值变动
3、收利息---交易性金融资产应收利息
4、公允价值变动损益

二、实例
1、	2007-8-29购入0781171  07澜沧江CP01   1年4.85%   100元/百元面值   起息日2007-3-5   到期日2008-3-5
 100.2944（单位净价）+0.01329（单位应计利息）=100.3077（单位全价 ）  
3,000万元（面值）+88,320（溢价）+3,986.30（应计利息）=30,092,306.30（结算金额）
成交日期：2007-8-29      全国银行间同业拆借中心银行间债券买卖买入成交通知单
买入方	甲方
卖出方	乙方
债券名称	07澜沧江CP01	债券代码	0781171
净价（元/百元面值）	100.2944	应计利息（元/百元面值）	0.01329
全价（元/百元面值）	100.3077	券面总额（元/百元面值）	3,000.00 
净价金额（元/百元面值）	30,088,320.00 	应计利息总额（元）	3,986.30 
全价金额（元）	30,092,306.30 	手续费（元）	75
交割日	2007-8-29	结算方式	券款对付
2007-8-29甲方会计分录：
借：交易性金融资产---成本                            30,088,320
应收利息---交易性金融资产应收利息                3,986.30
  贷：银行存款                                       30,092,306.30

2、在资产负债表日按分期付息、一次还本债券投资的票面利率计算的利息，当月买入于次月开始计提，按月计提应收利息  3000万元*4.85%*1个月/12个月=121,250元，2007-9-30会计分录：
借：应收利息---交易性金融资产应收利息                121,250
  贷：投资收益                                       121,250

3、2007-8-31公允价值为100.2944，即公允价值与成本相同，不做会计分录。
公允价值变动情况表如下：
日期	2007-8-29	2007-8-31	2007-9-30	2007-10-25
公允价值(净价）	100.2944(成本） 	100.2944	101	102（卖出）
4、2007-09-30公允价值为101元，公允价值较成本上涨。（101-100.2944）*3000万元=213,000元
借：交易性金融资产---公允价值变动                     211,680
贷：公允价值变动损益                                211,680

若跌价了做相反分录
借：公允价值变动损益 
  贷：交易性金融资产---公允价值变动

5、2007-10-25卖出102元，获资金30,831,205.48元，102+0.77068493=102.77068493
借：银行存款                                          30,831,205.48
  贷：交易性金融资产---成本                            30,088,320
应收利息---交易性金融资产应收利息                125,236.30
交易性金融资产---公允价值变动                    211,680
投资收益                                         405,969.18

6、结转本年利润 
借：投资收益                                           527,219.18
公允价值变动损益                                   211,680
  贷：本年利润                                         738,899.18


## 实际利率法计算及会计核算案例

按实际利率法进行溢折价摊销
一、	科目设置
1、	持有至到期投资---利息调整
2、	投资收益

二、溢价摊销
2007-1-1甲银行购买剩余期限为5年期债券，票面利率6%，分期付息，购入2亿元，购入价格为：
102.1（单位净价）+0（单位利息）=102.1(全价），到期收益率5.515%，溢价购入债券。
204,200,000（净价）+0（应计利息）=204,200,000（结算金额）
借：持有至到期投资----成本                        200,000,000
持有至到期投资---利息调整                     4,200,000
   贷：银行存款                                  204,200,000

年度	年初摊余成本	利息收入	现金流量	年末摊余成本	年摊销额
　	(万元）	摊余成本*实际利率	面值*票面利率	年初摊余成本+利息收入-现金流量	现金流量-利息收入 
2007	20,420.00 	1,126.16 	1,200.00 	20,346.16 	73.84 
2008	20,346.16 	1,122.09 	1,200.00 	20,268.25 	77.91 
2009	20,268.25 	1,117.79 	1,200.00 	20,186.04 	82.21 
2010	20,186.04 	1,113.26 	1,200.00 	20,099.30 	86.74 
2011	20,099.30 	1,100.69 	21,200.00 	0.00 	99.30 
合计	　	　	　	　	420.00 
1、2007-12-31溢价摊销
借：投资收益                                         738,400
  贷：持有至到期投资----利息调整                      738,400
同时计提当年利息收入
借：应收利息----持有至到期投资应收利息                12,000,000
   贷：投资收益                                      12,000,000
溢价摊销冲减利润11,261,600元，每年收到实际的利息收入冲销已计提的应收利息。

2、2008-12-31溢价摊销
2008-1-1收到利息
借：银行存款                                         12,000,000
  贷：应收利息----持有至到期投资应收利息              12,000,000
以后每年收到利息都做此分录。

借：投资收益                                         779,100                             
  贷：持有至到期投资----利息调整                      779,100           
同时计提当年利息收入

借：应收利息----持有至到期投资应收利息                 12,000,000
   贷：投资收益                                       12,000,000

3、2009-12-31溢价摊销
借：投资收益                                           822,100                
  贷：持有至到期投资----利息调整                        822,100
同时计提当年利息收入
借：应收利息----持有至到期投资应收利息                  12,000,000
   贷：投资收益                                        12,000,000

4、2010-12-31溢价摊销
借：投资收益                                            867,400
  贷：持有至到期投资----利息调整                         867,400
同时计提当年利息收入 
借：应收利息----持有至到期投资应收利息                   12,000,000
   贷：投资收益                                         12,000,000

5、2011-12-31溢价摊销
借：应收利息----持有至到期投资应收利息                   12,000,000
   贷：投资收益                                         12,000,000

借：投资收益                                             993,000
  贷：持有至到期投资----利息调整                          993,000

借：银行存款                                             200,000,000
   贷：持有至到期投资----成本                             200,000,000


三、折价摊销
2007-1-1甲银行购买剩余期限为5年期债券，票面利率5%，分期付息，购入5000万元，购入价格为：
88.02（单位净价）+0（单位利息）=88.02(全价），到期收益率8%，折价购入债券。
44,010,000（净价）+0（应计利息）=44,010,000（结算金额）
借：持有至到期投资----成本                                50,000,000
   贷：银行存款                                          44,010,000
持有至到期投资---利息调整                          5,990,000
年度	年初摊余成本	利息收入	现金流量	年末摊余成本	年摊销额
　	　	摊余成本*实际利率	面值*票面利率	年初摊余成本+利息收入-现金流量	利息收入-现金流量
2007	44,010,000.00 	3,520,800.00 	2,500,000.00 	45,030,800.00 	1,020,800.00 
2008	45,030,800.00 	3,602,500.00 	2,500,000.00 	46,133,300.00 	1,102,500.00 
2009	46,133,300.00 	3,690,700.00 	2,500,000.00 	47,324,000.00 	1,190,700.00 
2010	47,324,000.00 	3,785,900.00 	2,500,000.00 	48,609,900.00 	1,285,900.00 
2011	48,609,900.00 	3,890,100.00 	2,500,000.00 	0.00 	1,390,100.00 
合计	　	　	　	　	5,990,000.00 
1、2007-12-31折价摊销
借：持有至到期投资----利息调整                    1,020,800
  贷：投资收益                                   1,020,800

同时计提当年利息收入
借：应收利息----持有至到期投资应收利息            2,500,000
   贷：投资收益                                  2,500,000
折价摊销增加利润1,020,800元
，
2、2008-12-31折价摊销
2008-1-1收到利息
借：银行存款                                     2,500,000
  贷：应收利息----持有至到期投资应收利息          2,500,000
每年收到实际的利息收入冲销已计提的应收利息, 以后每年收到利息都做此分录.。

借：持有至到期投资----利息调整                    1,102,500
  贷：投资收益                                   1,102,500
同时计提当年利息收入
借：应收利息----持有至到期投资应收利息            2,500,000
   贷：投资收益                                  2,500,000

3、2009-12-31折价摊销
借：持有至到期投资----利息调整                    1,190,700
  贷：投资收益                                   1,190,700

同时计提当年利息收入
借：应收利息----持有至到期投资应收利息            2,500,000
   贷：投资收益                                  2,500,000

4、2010-12-31折价摊销
借：持有至到期投资----利息调整                    1,285,900
  贷：投资收益                                   1,285,900

同时计提当年利息收入 
借：应收利息----持有至到期投资应收利息            2,500,000
   贷：投资收益                                  2,500,000
折价摊销增加利润1，102，500元。

5、2011-12-31折价摊销
借：持有至到期投资----利息调整                    1,390,100
  贷：投资收益                                   1,390,100

借：应收利息----持有至到期投资应收利息            2,500,000
   贷：投资收益                                  2,500,000

借：银行存款                                     50,000,000
  贷：持有至到期投资----成本                      50,0


## 可供出售金融资产会计核算案例

可供出售金融资产-债券投资会计核算
一、科目设置
1、可供出售金融资产---成本（指面值）
2、可供出售金融资产---利息调整
3、可供出售金融资产---公允价值变动
4、应收利息----可供出售金融资产应收利息(用于分期付息、到期一次还本债券)
5、资本公积----其他资本公积
6、可供出售金融资产----应计利息（用于一次还本付息债券）

二、实例
成交日期：2007-8-2   全国银行间同业拆借中心银行间债券买卖买入成交通知单
买入方	甲方
卖出方	乙方
债券名称	03国债11	债券代码	030011
净价（元/百元面值）	103.2516	应计利息（元/百元面值）	2.15753
全价（元/百元面值）	105.4091	券面总额（元） 	13,000.00 
净价金额（元）	134,227,080.00 	应计利息总额（元）	2,804,794.52 
全价金额(元）	137,031,874.52 	手续费（元）	325.00 
交割日	2007-8-2	结算方式	券款对付
1、2007-8-2购入030011  03国债11   期限7年   100元/百元面值   票面利率3.5%      起息日2003-11-19    到期日2010-11-19      每年付息一次
借：可供出售金融资产---成本                             130,000,000
可供出售金融资产---利息调整                         4,227,080
应收利息----可供出售金融资产应收利息                2,804,794.52
贷：银行存款                                        137,031,874.52

2、每月计提应计利息，2007-8-31计提应收利息会计分录如下，以后每月依此类推：
借：应收利息----可供出售金融资产应收利息                379,166.67
贷：投资收益                                        379,166.67

3、	每月溢价摊销，4，227，080/39个月=108,386.67，实际利率法将在后面有专门讲解，在此不做详细计算。以此简单方法计算摊销额。2007-8-31溢折价摊销分录如下，以后每月依此类推：
借：投资收益                                            108,386.67
  贷：可供出售金融资产---利息调整                       108,386.67

4、2007-8-31日公允价值为103元 ( 103*13,000万)-( 13,000万+4,118,693.33)=-218,693.33
借：资本公积---其他资本公积                              218,693.33
   贷：可供出售金融资产---公允价值变动                   218,693.33
由中债提供的公允价值如下表所示，全部采用净价。
日期	2007-8-31	2007-9-30	2007-10-31	2007-11-30	2007-12-31	2008-1-15卖出
公允价值(净价）103.2516	103	102	100	98	96	99
5、2007-9-30公允价值为102元
借：资本公积---其他资本公积                             1,191,613.33
   贷：可供出售金融资产---公允价值变动                  1,191,613.33

6、2007-10-31公允价值为100元
借：资本公积---其他资本公积                              2,491,613.33
   贷：可供出售金融资产---公允价值变动                   2,491,613.33

7、2007-11-19收到利息4,550,000元,已计提3个月应收利息
借：银行存款                                              4,550,000
   贷：应收利息----可供出售金融资产应收利息               3,942,294.53
       投资收益                                           607,705.47

8、2007-11-30公允价值为98元
借：资本公积---其他资本公积                           2,491,613.33
   贷：可供出售金融资产---公允价值变动                2,491,613.33

9、2007-12-31公允价值为96元
借：资本公积---其他资本公积                              2,491,613.33
   贷：可供出售金融资产---公允价值变动                   2,491,613.33

10、2007-12-31年终跌价为96，计提减值准备(在此为方便案例讲解，不到二年也在此计提减准备）
借：资产减值损失                                            8，885，146.65
贷：资本公积—其他资本公积                                8，885，146.65

11、结转2007年本年利润
借：投资收益                                              1,961,605.47
    本年利润                                              6,923,541.18
   贷：资产减值损失                                       8,885,146.65

12、2008-1-15卖出
借：银行存款                                                129,410,547.94
可供出售金融资产---公允价值变动                         8,885,146.65
  贷：可供出售金融资产---成本                               130,000,000
可供出售金融资产---利息调整                           3,685,146.65
应收利息----可供出售金融资产应收利息                  758,333.34
投资收益                                              3,852,214.60

      13、结转2008年本年利润
借：投资收益                                               3,852,214.60
   贷：本年利润                                            3,852,214.60

14、2008-1-1可供出售重分类为持有至到期，条件：
1、企业的持有意图或能力发生改变，满足划分为持有至到期的要求。
2、可供出售的公允价值不再能可靠计量。
3、持有可供出售金融资产的期限超过2年。
借：持有至到期投资---成本                                       130,000,000
持有至到期投资---利息调整                                   3,685,146.65
应收利息----持有至到期投资应收利息                          758,333.34
可供出售金融资产---公允价值变动                             8,885,146.65
  贷：可供出售金融资产---成本                                   130,000,000
可供出售金融资产---利息调整                               3,685,146.65
应收利息----可供出售金融资产应收利息                      758,333.34
持有至到期投资减值准备                                    8,885,146.65
如果可供出售债券投资为一次还本付息的（贴现债），应收未收利息放在“可供出售金融资产----应计利息”内核算。

15、假设将持有至到期投资重分类为可供出售金融资产，可供出售要按公允价值记帐， 差额记入资本公积，防止利用重分类来调节利润。
借：可供出售金融资产---成本                                
可供出售金融资产---利息调整                            
可供出售金融资产---公允价值变动                    
应收利息----可供出售金融资产应收利息                    
持有至到期投资---减值准备
   贷：持有至到期投资---成本                                 
持有至到期投资---利息调整                            
应收利息----持有至到期投资应收利息                    
（借或贷）投资收益
（借或贷）资本公积—其他资本公积                       
      
## 持有至到期投资（分期付息、到期一次还本债券）会计核算案例

持有至到期投资（分期付息、到期一次还本债券）会计核算

一、科目设置
1、持有至到期投资---成本（即面值）
2、持有至到期投资---利息调整（即溢折价，到期收益率与票面利率的差额）
3、应收利息----持有至到期投资应收利息  
4、持有至到期投资减值准备

二、实例
2、	2007-1-22购入030004      03国债04  
期限：5年期   票面利率：2.45%  100元/百元面值    起息日：2003-4-24   到期日：2008-4-24  每年4月24日付息1次   分期付息债券     到期收益率：2.5274%
99.90（单位净价）+1.84（单位应计利息）=101.74（单位全价）
31，120，000（面值）+（-31,120）（折价）+572,352.22（应计利息）=31,661,232.22（结算金额）
成交日期：2007-1-22      全国银行间同业拆借中心银行间债券买卖买入成交通知单
买入方	甲方
卖出方	乙方
债券名称	03国债04	债券代码	030004
净价（元/百元面值）	99.9	应计利息（元/百元面值）	1.84
全价（元/百元面值）	101.74	券面总额（万元）	3,112.00 
净价金额（元/百元面值）	31,088,880.00 	应计利息总额（元）	572,352.22 
全价金额（元）	31,661,232.22 	手续费（元）	75
交割日	2007-1-22	结算方式	券款对付
2007-1-22会计分录：
借：持有至到期投资---成本                                 31,120,000
应收利息----持有至到期投资应收利息                    572,352.22
  贷：银行存款                                            31,661,232.22
持有至到期投资---利息调整                           31,120

3、	每月末计提应计利息，当月买入，次月起计提
借：应收利息----持有至到期投资应收利息                    63,536.67
  贷：投资收益                                            63,536.67

4、	溢价摊销   
借：投资收益                                 
   贷：持有至到期投资---利息调整              

4、每月末折价摊销    31,120（折价）/15个月=2,074.67（每月折价摊销额），按实际利率法进行溢折价摊销，在此为计算简便不作详述，后面将有详细阐述实际利率法。
借：持有至到期投资---利息调整                              2,074.67                 
  贷：投资收益                                             2,074.67

5、	2007年4月24日收到利息3112万元*2.45%*1年=762,440元
应计利息余额=572,352.22+63,536.67*2=699,425.56
借：银行存款                                               762,440
   贷：应收利息----持有至到期投资应收利息                  699,425.56
       投资收益                                            63,014.44      

6、2007-12-31年终跌价，公允价值为97.9元/百元面值，计提减值准备2元，共计622,400元
借：资产减值损失                                            622,400
  贷：持有至到期投资减值准备                                622,400

7、结转2007年本年利润
累计投资收益=63,536.67*11个月+2,074.67*11个月+63,014.44=784,739.18
借：投资收益                                                784,739.18
  贷：资产减值损失                                          622,400
      本年利润                                              162,339.18

8、2008-4-24到期3,112万本金+762,440利息=31,882,440元
借：银行存款                                                31,882,440.00
    持有至到期投资----利息调整                              2074.62
持有至到期投资减值准备                                  622,400.00
贷：持有至到期投资---成本                                 31,120,000
应收利息----持有至到期投资应收利息                    762,440.04
投资收益                                              624,474.58

9、结转2008年本年利润
累计计提的应计利息=63,536.67*3=190,610.01
累计折价摊销=2,074.67*3=6224.01
累计投资收益=190,610.01+6,224.01+624,474.58=821,308.60
借：投资收益                                                821,308.60
  贷：本年利润                                              821,308.60

10、假设2008-2-10将持有至到期投资重分类为可供出售金融资产，条件：
1、出售了一部分已划为持有至到期的投资：余期5年的,在已确定好1个亿的030004国债持有至到期投资，在第三年卖出2000万，剩余的8000万应划分为可供出售类，以公允价值进行后续计量。以后2年不得再将030004划入持有至到期内。
2、以上例起始金额为例，将030004进行重分类，会计分录如下：
重分类当天公允价值为101元+1.96=102.96 
31,120,000（面值）+311,200（溢价）+609,952（应收利息）=32,041,152元结算金额
 借：可供出售金融资产—-成本                                 31,120,000
     应收利息---可供出售金融资产应收利息                     635,366.70
持有至到期投资---利息调整                               6,223.96
持有至到期投资减值准备                                  622,400
   贷：持有至到期投资---成本                                 31,120,000
应收利息----持有至到期投资应收利息                    635,366.70
资本公积----其他资本公积                              622,400
可供出售金融资产—利息调整                            6,223.96


8、	持有至到期投资（一次还本付息债券）会计核算案例

持有至到期投资（一次还本付息债券）会计核算
一、科目设置
1、持有至到期投资---成本（即面值）
2、持有至到期投资---利息调整
3、持有至到期投资---应计利息
4、持有至到期投资减值准备
持有至到期投资以摊余成本计量。

二、实例
5、	2007-8-22一级市场中标0701091中央银行票据
07央行票据91债券发行认购额和缴款通知书
债券名称	07央票97	债券代码	0701097
发行价格（元/百元面值）	96.88	票面利率（%）	3.2205
中标价位（元/百元面值）	96.88	中标额（万元）	40,000.00 
缴款金额（元）	387,520,000.00 	缴款日	2007-8-22

 07央行票据91    0701091  期限 1年  票面利率3.2205%    起息日2007-8-22     到期日2008-8-22    一次还本付息债券
 96.88（单位净价）+3.12（单位应计利息）=100（全价）
387,520,000（净价） +12,480,000（应计利息）=400,000,000（全价）
借：持有至到期投资---成本                                387,520,000
  贷：银行存款                                           387,520,000

2、每月末计提应计利息，当月买入于次月计提，2007年计提4个月     4亿*3.2205%*1个月/12=1,073,500
借：持有至到期投资---应计利息                            1,073,500
  贷：投资收益                                           1,073,500
（借或贷） 持有至到期投资---利息调整 
如有溢折价的进行溢折价摊销

3、2007-12-31年终跌价为95，计提减值准备1.88元，共计7,520,000元
借：资产减值损失                                          7,520,000
  贷：持有至到期投资减值准备                              7,520,000

4、结转2007年当年利润
借：投资收益                                              4,294,000
本年利润                                              3,226,000
  贷：资产减值损失                                        7,520,000

5、2008年继续每月末计提应计利息，2008年计提7个月的利息
借：持有至到期投资---应计利息                              1,073,500
  贷：投资收益                                             1,073,500
（借或贷） 持有至到期投资---利息调整

6、2008-8-22到期 
 12,480,000（全额利息）- 1,073,500*4（2007年度已计提的利息）-1,073,500*7（2008年已计提的7个月的利息）= 12,480,000-4,294,000-7,514,500
=12,480,000-11,808,500
=671,500
671,500+7,520,000=8,191,500
借：银行存款                                                 400,000,000
持有至到期投资减值准备                                   7,520,000
  贷：持有至到期投资---成本                                  387,520,000
持有至到期投资---应计利息                              11,808,500
投资收益                                               8,191,500

7、结转2008年本年利润
1,073,500（每月计提的利息）*7个月+8,191,500=15,706,000
借：投资收益                                                15,706,000
  贷：本年利润                                              15,706,000

2007年利润+2008年利润=（-3,226,000）+15,706,000=12,480,000
(本金)387,520,000+(利息)12,480,000=400,000,000（全额）


9、	买断式正回购会计核算案例

买断式正回购会计核算
一、科目设置
交易性金融资产---成本
交易性金融资产---公允价值变动
应收利息----交易性金融资产应收利息
交易性金融负债----成本
交易性金融负债---公允价值变动
应付利息----交易性金融负债应付利息

二、实例
06国债13  060013  期限：7年期   票面利率：2.89%   100元/百元面值   起息日：2006-8-31     到期日2013-8-31
2007年4月8日060013在交易类债券中列示。情况如下：
债券名称	债券代码	面值 	溢 价	应计利息	合计
06国债13	060013	元	元	元	元
		100.000 	0.056 	3.459 	103.515 
		130,000,000.00 	72,827.12 	2,191,066.47 	132,263,893.59 
 “交易性金融资产---成本”余额                      130,072,827.12
“应收利息----交易性金融资产应收利息”余额         2,191,066.47
交易性金融资产余额                                 132,263,893.59
2007年4月9日甲方用该笔交易类债券做买断式正回购，形成成交单如下：
成交日期：2007-4-9      全国银行间同业拆借中心银行间买断式回购正回购成交通知单
正回购方	甲方
逆回购方	乙方
债券名称	06国债13	券面总额（万元）	13000
回购期限（天）	90	回购利率（%）	3
首期交易净价（元/百元面值）	100.06	到期交易净价（元/百元面值）	100.1005
首期结算日应计利息（元/百元面值）	1.74984	首期结算日应计利息（元/百元面值）	2.4624
首期交易全价（元/百元面值）	101.8098	到期交易全价（元/百元面值）	102.5629 
首期资金支付额（元）	132352786.30 	到期资金支付额（元）	133331834.31 
首期结算日	2007-4-9	到期结算日	2007-7-8
首期结算方式	券款对付	到期结算方式	券款对付
（一）、甲方2007-4-9买断式正回购首期（卖出）结算日会计分录如下：
买断式正回购首期（卖出）价格
100．06（单位净价）+1.74984（应计利息）=101.8098（全价）
13,000万+78,000+2,274,786.30=132,352,786.30
借：银行存款                                          132,352,786.30
贷：交易性金融负债----成本                          130,078,000
    应付利息----交易性金融负债应付利息              2,274,786.30
其他金融负债应当其公允价值和相关交易费用之和作来初始确认金额，其他金融负债通常采用实际利率法，应按摊余成本进行后续计量。使甲方同时拥有一项资产同时也有一项负债，在资产负债表中分别列示。

（二）交易性金融资产继续进行后续计量
1、2007-4-30交易性金融资产继续每月计提应收利息，
交易类不进行溢折价摊销。甲方不得因为没有债券而不再衡量该债券的风险与收益。国债公司也应将买断式回购单独列示，不得显示没有债券余额，因为买断式正回购业务同时形成一项资产与一项负债，并且在资产负债表分别列示，不得抵销。
13000万元*2.89%*1/12个月=313,083.33元
借：应收利息---交易性金融资产应收利息                     313,083.33
   贷：投资收益                                           313,083.33

2、2007-4-30交易性金融资产按公允价值继续计量99*13,000万-72,827.12-13,000万=-1,372,827.12元
借：公允价值变动损益                                      1,372,827.12
   贷：交易性金融资产----公允价值变动                     1,372,827.12
日期	2007-4-9	2007-4-30	2007-5-31	2007-6-30
公允价值(净价）	100.056(成本） 	99	98	96

3、2007-5-31交易性金融资产继续每月计提应收利息
借：应收利息---交易性金融资产应收利息                      313,083.33
   贷：投资收益                                            313,083.33

4、2007-5-31交易性金融资产按公允价值继续计量（98-99）*13,000万=-1,300,000元
借：公允价值变动损益                                       1,300,000
   贷：交易性金融资产----公允价值变动                      1,300,000

5、2007-6-30交易性金融资产继续每月计提应收利息
借：应收利息---交易性金融资产应收利息                      313,083.33
   贷：投资收益                                            313,083.33

6、2007-6-30交易性金融资产按公允价值继续计量（96-98）*13,000万=-2,600,000元
借：公允价值变动损益                                       2,600,000
   贷：交易性金融资产----公允价值变动                      2,600,000

7、2007-7-8交易性金融资产状况如下
交易性金融资产----成本借方余额130，072，827.12元
交易性金融资产----公允价值变动贷方余额5,272,827.12元
应收利息-----交易性金融资产应收利息3,130，316.46元
交易性金融资产获得的利润=利息收入+公允价值变动损益
=（313,083.33*3*-（1,372,827.12+1,300,000+2,600,000）
=939,249.99-5,272,827.12
=-4,333,577.13

交易性金融资产随着公允价值的不断下跌，（100.056到96）亏损日益增加。

（三）交易性负债继续进行后续计量

1、2007-4-30交易性金融负债同时开始计量，计提应付利息
借：投资收益                                                313,083.33
  贷；应付利息----交易性金融负债应付利息                    313,083.33

2、2007-4-30交易性金融负债按公允价值继续计量99*13,000万-78,000-13,000万=-1,378,000元
借：交易性金融负债-----公允价值变动                           1,378,000
   贷：公允价值变动损益                                       1,378,000

060013公允价值变动表：
日期	2007-4-9	2007-4-30	2007-5-31	2007-6-30
公允价值(净价）	100.06(成本） 	99	98	96

3、2007-5-31交易性金融负债继续每月计提应付利息
借：投资收益                                                  313,083.33
贷；应付利息----交易性金融负债应付利息                     313,083.33

4、2007-5-31交易性金融负债按公允价值继续计量（98-99）*13,000万=-1,300,000元
借：交易性金融负债-----公允价值变动                            1,300,000
   贷：公允价值变动损益                                        1,300,000

5、2007-6-30交易性金融负债继续每月计提应付利息
借：投资收益                                                  313,083.33
  贷；应付利息----交易性金融负债应付利息                        313,083.33

6、2007-6-30交易性金融负债按公允价值继续计量（96-98）*13,000万=-2,600,000元
借：交易性金融负债-----公允价值变动                             2,600,000
   贷：公允价值变动损益                                         2,600,000

7、甲方2007-7-8买断式正回购到期（买入）结算日会计分录如下:
2007-7-8买断式正回购到期（买入）价格
100.1005+2.4624=102.5629
1.3亿元+130,650+3,201,184.31=133,331,834.31
借: 交易性金融负债----成本                                       130,078,000
应付利息---交易性负债应付利息                                3,214,036.29
投资收益                                                     5,317,798.02
贷：银行存款                                                   133,331,834.31
交易性金融负债----公允价值变动                              5,278,000

8、2007-7-8交易性金融负债状况如下
交易性金融负债----成本贷方余额130,078,000元 
交易性金融负债----公允价值变动借方余额5,278,000元
应付利息-----交易性金融负债应付利息贷方余额3,214,036.29元
公允价值变动损益贷方余额5,278,000元
投资收益0


（四）、结转本年利润
借：公允价值变动损益                                        5,172.88
本年利润                                                5,312,625.14
贷：投资收益                                              5,317,798.02
    

10、	买断式逆回购会计核算案例

买断式逆回购会计核算
一、	科目设置 
1、	交易性金融资产
2、	可供出售金融资产

二、实例：债券要素如下：
成交日期：2007-4-24      全国银行间同业拆借中心银行间买断式回购逆回购成交通知单
逆回购方	甲方
正回购方	乙方
债券名称	06中电信CP01	券面总额（万元）	10000
回购期限（天）	16	回购利率（%）	2.0076
首期交易净价（元/百元面值）	100.68	到期交易净价（元/百元面值）	100.635
首期结算日应计利息（元/百元面值）	0.10863	首期结算日应计利息（元/百元面值）	0.24233
首期交易全价（元/百元面值）	100.7886	到期交易全价（元/百元面值）	100.8773 
首期资金支付额（元）	100,788,630.14 	到期资金支付额（元）	100,877,328.77 
首期结算日	2007-4-24	到期结算日	2007-5-10
首期结算方式	券款对付	到期结算方式	券款对付
甲方会计分录：
1、2007-4-24买断式逆回购首期表现为买入，将其列入交易性资产
100（单位净价）+0.68（溢价）+0.10863（应计利息）=100.7886（单位全价）
10,000万元（面值）+680,000（溢价）+108,630.14（应计利息）=100,788,630.14（全价）
借：交易性金融资产---成本                             100,680,000
应收利息---交易性金融资产应收利息                 108,630.14
   贷：银行存款                                       100,788,630.14
买断式逆回购首期买入的债券每到资产负债表日要按公允价值进行计量。

2、2007-4-30以公允价值计量，公允价值为101元
101*10,000万元-680,000元-10,000万元=320,000元
借：交易性金融资产---公允价值变动                     320,000
   贷：公允价值变动损益                               320,000
当月买入的债券次月按票面利率计提应收利息，因期限较短本例中暂不计提。因期限较短本例中暂不进行溢价摊销。实际工作中均要进行计提与摊销。
借：应收利息---交易性金融资产应收利息
  贷：投资收益

3、2007-5-10买断式回购到期卖出
借：银行存款                                           100,877,328.77
     投资收益                                          231,301.37
  贷：交易性金融资产---成本                            100,680,000
      应收利息----交易性金融资产应收利息               108,630.14
      交易性金融资产---公允价值变动                    320,000

4、2007-12-31结转本年利润
借：公允价值变动损益                                   320,000
  贷：本年利润                                         88,698.63
      投资收益                                         231,301.37


11、	远期买入交易会计核算案例

远期买入交易会计分录
一、科目设置：
1、衍生工具---远期买入交易                            
2、公允价值变动损益

二、实例
 2007-9-10日约定5个月后在2008-02-10以101.437元 买入050013债券资产5000万元
05国债13   050013  期限：7年期   票面利率：3.01%  起息日：2005-11-25   到期日：2012-11-25    每年付息一次
成交日期：2007-9-10             全国银行间同业拆借中心银行间债券远期买方成交通知单
买入方	甲方
卖出方	乙方
债券名称	05国债13	债券代码	050013
远期交易期限（天）	153	远期收益率（%）	2.7107
交易净价（元）	101.437	结算日应计利息（元）	2.284
交易全价（元）	103.721	券面总额（万元） 	5,000.00 
净价金额（元）	50,718,500.00 	结算日应计利息总额（元）	1,142,150.68 
结算日	2008-2-10	全价金额（元）	51,860,650.68 
结算方式	券款对付	手续费（元）	125.00 
买入方保证金（券）金额（元）	　	卖出方保证金（券）金额（元）	　
买入方保证券简称	　	卖出方保证券简称	　
保证金（券）提交日期	　	是否允许变更保证金（券）	　
1、2007-9-10甲方会计分录：
借：衍生工具----远期买入交易                                 0
  贷：银行存款                                              0
如果有保证金的
借：应收保证金
   贷：银行存款
这笔一定要做，在系统中做一个记录为保证后续计量。

2、2007-9-30资产负债表日按公允价值计量，公允价值净价为102元
借：衍生工具---远期买入交易                                51,000,000
 贷：公允价值变动损益                                     51,000,000

公允价值低于其帐面余额的差额做相反的会计分录。公允价值变动情况表：
日期	2007-9-10	2007-9-30	2007-10-31	2007-11-30	2007-12-31	2008-1-31
公允价值(净价）	0 	102	100	99.2	98	99.4
3、2007-10-31资产负债表日按公允价值计量，公允价值净价为100元。
5,000万元*（100-102）=-1000000
借：公允价值变动损益                            1,000,000
  贷：衍生工具---远期买入交易                    1,000,000

4、2007-11-30资产负债表日按公允价值计量，公允价值净价为99.2元。
5,000万元*（99.2-100）=-400,000
借：公允价值变动损益                              400,000
  贷：衍生工具---远期买入交易                      400,000

5、2007-12-31资产负债表日按公允价值计量，公允价值净价为98元。
5,000万元*（98-99.2）=-600,000
借：公允价值变动损益                              600,000
  贷：衍生工具---远期买入交易                      600,000

6、结转2007年本年利润
借：公允价值变动损益                              49,000,000
   贷：本年利润                                   49,000,000


7、2008-1-31资产负债表日按公允价值计量，公允价值净价为99.4元。
5,000万元*（99.4-98）=700,000
借：衍生工具---远期买入交易                        700,000
 贷：公允价值变动损益                           700,000

8、2008-2-10发生实际的资金交割和债券过户，买入的债券拟放在持有至到期帐户内核算，会计分录：
借：持有至到期投资---成本                           50,000,000
    持有至到期投资----利息调整                      718,500        
应收利息---持有至到期投资应收利息               1,142,150.68
    公允价值变动损益                               49,700,000
  贷：银行存款                                     51,860,650.68
衍生工具---远期买入交易                       49,700,000

如果有保证金的到期退还保证金
借：银行存款
   贷：应收保证金 

9、结转2008年本年利润
借：本年利润                                        49,000,000
   贷：公允价值变动损益                             49,000,000


12、	远期卖出交易会计核算案例

远期卖出交易会计分录
一、科目设置：
1、衍生工具---远期卖出交易                            
2、公允价值变动损益

二、实例
2007-9-10日约定5个月后在2008-02-10以 101.437元的价格卖出050013债券资产5000万元
05国债13   050013  期限：7年期   票面利率：3.01%  起息日：2005-11-25   到期日：2012-11-25    每年付息一次
假定拟卖出的远期债券原来归类为交易类帐户。
100（单位净价）+1.2（应计利息）=101.20
50,000,000+600,000=50,600,000，交易性资产依然要按照其会计核算办法进行资产的核算，但同时形成了一项因衍生工具形成的负债。
成交日期：2007-9-10      全国银行间同业拆借中心银行间债券远期卖方成交通知单
卖出方	甲方
买入方	乙方
债券名称	05国债13	债券代码	050013
远期交易期限（天）	7	远期收益率（%）	2.7107
交易净价（元）	101.437	结算日应计利息（元）	2.284
交易全价（元）	103.721	券面总额（万元） 	5,000.00 
净价金额（元）	50,718,500.00 	结算日应计利息总额（元）	1,142,150.68 
结算日	2008-2-10	全价金额（元）	51,860,650.68 
结算方式	券款对付	手续费（元）	125.00 
买入方保证金（券）金额（元）	　	卖出方保证金（券）金额（元）	　
买入方保证券简称	　	卖出方保证券简称	　
保证金（券）提交日期	　	是否允许变更保证金（券）	　

（一）远期卖出交易会计分录
1、2007-9-10甲方会计分录：
借：银行存款                                                         0
  贷：衍生工具---远期卖出交易                                         0
这笔一定要做，在系统中做一个记录为保证后续计量。
如果有保证金的
借：应收保证金
   贷：银行存款

2、2007-9-30资产负债表日按公允价值继续计量原属于交易性债券资产的050013，公允价值净价为102元，102*5,000万元=51,000,000
借：公允价值变动损益                                            51,000,000
 贷：衍生工具---远期卖出交易                                     51,000,000

公允价值变动情况表如下：
日期	2007-9-10	2007-9-30	2007-10-31	2007-11-30	2007-12-31	2008-1-31
公允价值(净价）	100(成本） 	102	100	99.2	98	99.4

3、2007-10-31资产负债表日按公允价值计量，公允价值净价为100元，5000万元*（100-102）=-1,000,000 
借：衍生工具---远期卖出交易                                      1,000,000
  贷：公允价值变动损益                                          1,000,000

4、2007-11-30资产负债表日按公允价值计量，公允价值净价为99.2元，5000万元*（99.2-100）=-400，000
借：衍生工具---远期卖出交易                                      400,000
  贷：公允价值变动损益                                          400,000

5、2007-12-31资产负债表日按公允价值计量，公允价值净价为98元，5000万元*（98-99.2）=-600,000
借：衍生工具--远期卖出交易                                        600,000
  贷：公允价值变动损益                                            600,000

6、2008-1-31资产负债表日按公允价值计量，公允价值净价为99.4元，5000万元*（99.4-98）=700,000
借：公允价值变动损益                                             700,000
 贷：衍生工具---远期卖出交易                                    700,000

（二）交易性金融资产会计分录
05国债13   050013  期限：7年期   票面利率：3.01%  起息日：2005-11-25   到期日：2012-11-25    每年付息一次
假定拟卖出的远期债券原来归类为交易类帐户。
100（单位净价）+1.2（应计利息）=101.20
50,000,000(交易性金融资产---成本)+600,000（应收利息---交易性金融资产应收利息）=50,600,000（全价金额），交易性资产依然要按照其会计核算办法进行资产的核算，
1、2007-9-30资产负债表日公允价值为102元/百元面值，(102-100)*5000万元=1,000,000， 会计分录：
借：交易性金融资产---公允价值变动                                 1,000,000
  贷：公允价值变动损益                                           1,000,000
计提应收利息
借：应收利息-----交易性金融资产应收利息                             125,416.67
   贷：投资收益                                                   125,416.67

2、2007-10-31资产负债表日公允价值为100元/百元面值，(100-102)*5000万元=-1,000,000，会计分录：
借：公允价值变动损益                                               1,000,000
  贷：交易性金融资产---公允价值变动                                 1,000,000
计提应收利息
借：应收利息-----交易性金融资产应收利息                             125,416.67
   贷：投资收益                                                    125,416.67

3、2007-11-25收到利息1,505,000元
借：银行存款                                                       1,505,000
  贷：应收利息---交易性金融资产应收利息                             850,833.34
      投资收益                                                     654,166.66

4、2007-11-30资产负债表日公允价值为99.2元/百元面值，(99.2-100)*5000万元=400，000，会计分录：
借：公允价值变动损益                                                400,000
  贷：交易性金融资产---公允价值变动                                  400,000
计提应收利息
借：应收利息-----交易性金融资产应收利息                              125,416.67
   贷：投资收益                                                    125,416.67

5、2007-12-31资产负债表日公允价值为98元/百元面值，(98-99.2)*5000万元=-600,000，会计分录：
借：公允价值变动损益                                                600,000
  贷：交易性金融资产---公允价值变动                                  600,000
计提应收利息
借：应收利息-----交易性金融资产应收利息                              125,416.67
   贷：投资收益                                                    125,416.67

6、2008-1-31资产负债表日公允价值为99.4元/百元面值，(99.4-98)*5000万元=700,000，会计分录：
借：交易性金融资产---公允价值变动                                    700,000
  贷：公允价值变动损益                                              700,000
计提应收利息
借：应收利息-----交易性金融资产应收利息                               125,416.67
   贷：投资收益                                                     125,416.67

(三) 2008-2-10发生实际的资金交割和债券过户，
1、卖出的债券根据其原来在投资中的分类，分别销去帐面余额，会计分录：
借：银行存款                                                        51,860,650.68
衍生工具---远期卖出交易                                         49,700,000
交易性金融资产----公允价值变动                                  300,000
贷：交易性金融资产---成本                                         50,000，000
      应收利息---交易性金融资产应收利息                             376,250.01                       
      投资收益                                                     51,484,400.67
如果有保证金的,退回保证金
借：银行存款
   贷：应收保证金

2、结转2007年利润
借：投资收益                                                     1,155,833.34
本年利润                                                     48,844,166.66
贷：公允价值变动损益 （交易性金融资产）                       1,000,000
    公允价值变动损益（衍生工具）                              49,000,000

3、结转2008年利润
借：投资收益                                                  51,609,817.34
贷：本年利润                                               51,609,817.34

4、(2007年利润)-48,844,166.66+（2008年利润）51,609,817.34=2,765,650.68（总利润）


13、	资产支持证券会计核算案例

资产支持证券会计核算方法
一、科目设置 
资产支持证券---成本
资产支持证券---利息调整
应收利息----资产支持证券应收利息 (分期付息、一次还本债券) 
资产支持证券---减值准备
资产支持证券---应计利息（贴现债、一次还本付息债券）

二、实例
6、	2007-8-29购入资产支持证券一笔： 
 100.2944（单位净价）+0.01329（单位应计利息）=100.3077（全价）
3,000万（面值）+88,320（溢价）+3,986.30（应计利息）=30,092,306.30（结算金额）
借：资产支持证券---成本                              30,000,000
资产支持证券---利息调整                          88,320
应收利息----资产支持证券应收利息                 3,986.30
  贷：银行存款                                       30,092,306.3

7、	每月计提应计利息
借：应收利息----持有至到期投资应收利息
  贷：投资收益

8、	溢价摊销
借：投资收益
  贷：资产支持证券---利息调整

4、折价摊销
借：资产支持证券---利息调整
  贷：投资收益

6、	收到利息
借：银行存款                                        
   贷：应收利息----资产支持证券应收利息             
       投资收益                                      

6、2007-12-31年终跌价为98.2944，计提减值准备2元，共计600，000元
借：资产减值损失                                 600，000
  贷：资产支持证券---减值准备                    600，000

7、2008-1-25到期
借：银行存款
资产支持证券---减值准备
  贷：资产支持证券---成本
资产支持证券---利息调整
应收利息----资产支持证券应收利息          
（借或贷）投资收益

8、结转本年利润
借：投资收益
  贷：资产减值损失
      本年利润
